@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":FilterClientCommand" as FilterClientCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant ":FilteredList<Person>" as FilteredPersons MODEL_COLOR
participant ":FilteredList<Property>" as FilteredProperties MODEL_COLOR
end box

[-> FilterClientCommand : execute(...)
activate FilterClientCommand

FilterClientCommand -> ModelManager : updateFilteredPersonList(predicate)
activate ModelManager

ModelManager -> FilteredPersons : setPredicate(predicate)
activate FilteredPersons

FilteredPersons --> ModelManager
deactivate FilteredPersons

ModelManager --> FilterClientCommand
deactivate ModelManager

FilterClientCommand -> ModelManager : updateFilteredPropertyList(predicate)
activate ModelManager

ModelManager -> FilteredProperties : setPredicate(propertiesOfFilteredClients)
activate FilteredProperties

FilteredProperties --> ModelManager
deactivate FilteredProperties

ModelManager --> FilterClientCommand
deactivate ModelManager

[<-- FilterClientCommand : new CommandResult(...)
deactivate FilterClientCommand
@enduml
